/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class ConexionMysql implements Conexion{
    
    private static ConexionMysql mysql = null;
    private static String userName;
    private static String host;
    private static String database;
    private static String password;
    
    private Connection conexion;
    
    public static void setData(String user, String url, String db, String pw){
        userName = user;
        host = url;
        database = db;
        password = pw;
    }
    
    public static ConexionMysql getInstance(){
        if(mysql == null){
            mysql = new ConexionMysql(database, host, userName, password);
        }
        return mysql;
    }
    
    public static void CloseConexion() {
        try{
            mysql.close();
            mysql = null;
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, String.format("Error en la conexion: %s", ex.getMessage()), JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public PreparedStatement sentencia(String querySQL) throws SQLException{
        return this.conexion.prepareStatement(host);
    }
    
    public PreparedStatement sentenciaEspecial(String querySQL, int autoGeneratedKeys) throws SQLException{
        return this.conexion.prepareStatement(host, autoGeneratedKeys);
    }
    
    private ConexionMysql (String database, String host, String userName, String password){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            this.conexion = DriverManager.getConnection(String.format("jdbc:mysql://%s/%s", host, database), userName, password);
            
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, String.format("Error en la conexion: %s", ex.getMessage()), JOptionPane.ERROR_MESSAGE);
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex, String.format("Error en la conexion: %s", ex.getMessage()), JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void close() throws SQLException{
        this.conexion.close();
    }
    
    public static void main(String[] args) throws SQLException{
        ConexionMysql.setData("root", "localhost", "viajes", "chocolate4194");
        Conexion c = ConexionMysql.getInstance();
        c.close();
    }
    
}
