/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexion;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author jesus
 */
public interface Conexion {
    
    public PreparedStatement sentencia(String querySQL) throws SQLException;
    public PreparedStatement sentenciaEspecial(String querySQL, int autoGeneratedKeys) throws SQLException;
    public void close() throws SQLException;
}
